main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('data/', views.fungsi_data),
    path('signup/', views.signup, name='signup'),
    path('login/', views.Login, name='login'),
    path('logout/', views.Logout, name='logout')
    
]

story9/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

main/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.http import JsonResponse
import requests
import json
from .forms import SignUpForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

def home(request):
    return render(request, 'main/home.html')

def fungsi_data(request):
    url = "https://www.googleapis.com/books/v1/volumes?q=" + request.GET['q']
    ret = requests.get(url)
    #print(ret.content)
    data = json.loads(ret.content)
    #data = {"hehe":"hehe"}
    return JsonResponse(data, safe=False)


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('main:home')
    else:
        form = SignUpForm()
    return render(request, 'main/signup.html', {'form': form})


def Login(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('main:home')
        else:
            messages.info(request, 'Username or password is incorrect')
    context = {}
    return render(request, 'main/login.html', context)

def Logout(request):
    logout(request)
    return redirect('main:home')

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<title>st0ry9</title>
{% endblock meta %}

{% block content %}
  <input id="keyword" placeholder="Masukkan kata kunci">
  {% if not user.is_authenticated %}
  <p> Tolong log in terlebih dahulu untuk mencari buku </p>
  <p> Bila belum mempunyai akun silahkan sign up </p>
  {% endif %} 
  <ol id="daftar_isi">
  
  </ol>
  <script type ="text/javascript">
  $("#keyword").keyup( function(){
      var ketikan = $("#keyword").val();
      //console.log(ketikan);
      
      //membaca teknik ajax
      {% if user.is_authenticated %}
      $.ajax({
          url: "/data?q=" + ketikan,  
          success: function(data){
          var hasil = "/data?q=" + ketikan;
          console.log(hasil);
//            console.log(data);
            var arr_items = data.items;
//            console.log(arr_items);
           $("#daftar_isi").empty();
            for (i = 0; i < arr_items.length; i++) {
                var judul = arr_items[i].volumeInfo.title;
                var gambar = arr_items[i].volumeInfo.imageLinks.smallThumbnail;
                //console.log(judul);
                $("#daftar_isi").append("<li>" + judul + "<br><img src=" + gambar +">" +"</li>");
              } 
          }
      });  
      {% endif %} 
  });
  </script>
{% endblock content %}

main/templates/main/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h2>Welcome Back!!</h2>
  <form method="post">
    {% csrf_token %}
    <label for="username">username: </label>
    <input id="username" type="text" name="username" value="{{ username }}">
    <br>
    <label for="password">password: </label>
    <input id="password" type="password" name="password" value="{{ password }}">
    <br>
    <button type="submit">Login</button>
  </form>
<h4>Don't have an account?  <a style="color: #2D6BB4;" href="{% url 'main:signup' %}">Sign Up</a></h4> 
{% endblock %}

main/templates/main/signup.html
{% extends 'base.html' %}
{% load static %}
<!------ Include the above in your HEAD tag ---------->
{% block meta %}

{% endblock meta %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% include 'navbar.html' %}
  {% block content %}
  {% endblock content %}
</body>

</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    {% if user.is_authenticated %}
    <ul class="nav navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main:logout' %}"><span class="glyphicon glyphicon-log-in"></span> LogOut</a></li>
      </li>
      <li class="nav-item active">
        <span class="glyphicon glyphicon-user"></span> Welcome, {{ user.get_username }}. Thanks for logging in.</a></li>
      </li>
    </ul>
    <p></p>
    {% else %}
    <ul class="nav navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'main:signup' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </li>
    </ul>
    <p>Welcome, new user. Please log in.</p>
    {% endif %}
    
  </div>
</nav>